### ISSUE TITLE
Papers about this project

### ISSUE THREAD

**Issue by interestingtj** [jiaxin-scu/lie_detection#2]
Hi. Is there any papers about your project lie_detection? I was wondering if I can learn more about the project.

**Comment by jiaxin-scu** [comment]
你好，我是一名大三的学子，这是我主持的省级大创项目，我上传的代码只是我第一阶段的成果，第一阶段的成果有很多缺点，主要就是语音测谎没做好，数据集不够，如果你对我的项目感兴趣的话，可以从这两个方面去完善。我的论文还没有写，在导师的指导下，我开始了第二阶段的研究，目前我正在完善语音测谎以及模型融合，准备出了成果再写论文。同时我还在准备保研，要参加比赛，项目进度也拖的有点慢。毕竟不是我一个人的项目，没有同组成员的同意，一些关键性的数据、重要成果、代码我也不好发出来，如果你想了解更多的话，我在github上传了一个之前我答辩用的PPT，里面基本上描述了我们小组之前一段时间研究的思路和成果，希望能够帮到你。
Hello, I am a third-year university student. This is a provincial-level project that I presided over. The code I uploaded is only the result of my first phase. The first phase of the results has many shortcomings, mainly because the voice polygraph is not good and the data set is not enough. If you are interested in my project, you can improve it from these two aspects. My thesis has not been written yet, and under the guidance of my supervisor, I started the second phase of research. I am currently improving the voice polygraph and model fusion, and I will write the thesis after I have produced the results. At the same time, I'm preparing for postgraduate recommendation and I have to participate in the competition, so the progress of the project is a bit slow. After all, it's not my own project, without the consent of other members of the same group, I can't directly send out some key data, important results, and codes. If you want to know more, I posted a PPT of my defense on Github, which describes the ideas and results of our group's research. I hope it can help you.

**Comment by jiaxin-scu** [comment]
你好，我是一名大三的学子，这是我主持的省级大创项目，我上传的代码只是我第一阶段的成果，第一阶段的成果有很多缺点，主要就是语音测谎没做好，数据集不够，如果你对我的项目感兴趣的话，可以从这两个方面去完善。我的论文还没有写，在导师的指导下，我开始了第二阶段的研究，目前我正在完善语音测谎以及模型融合，准备出了成果再写论文。同时我还在准备保研，要参加比赛，项目进度也拖的有点慢。毕竟不是我一个人的项目，没有同组成员的同意，一些关键性的数据、重要成果、代码我也不好发出来，如果你想了解更多的话，我在github上传了一个之前我答辩用的PPT，里面基本上描述了我们小组之前一段时间研究的思路和成果，希望能够帮到你。
	Hello, I am a third-year university student. This is a provincial-level project that I presided over. The code I uploaded is only the result of my first phase. The first phase of the results has many shortcomings, mainly because the voice polygraph is not good and the data set is not enough. If you are interested in my project, you can improve it from these two aspects. My thesis has not been written yet, and under the guidance of my supervisor, I started the second phase of research. I am currently improving the voice polygraph and model fusion, and I will write the thesis after I have produced the results. At the same time, I'm preparing for postgraduate recommendation and I have to participate in the competition, so the progress of the project is a bit slow. After all, it's not my own project, without the consent of other members of the same group, I can't directly send out some key data, important results, and codes. If you want to know more, I posted a PPT of my defense on Github, which describes the ideas and results of our group's research. I hope it can help you.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jiaxin-scu/lie_detection"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月15日(星期天) 晚上6:54
收件人:&nbsp;"jiaxin-scu/lie_detection"<lie_detection@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[jiaxin-scu/lie_detection] Papers about this project (#2)





 
Hi. Is there any papers about your project lie_detection? I was wondering if I can learn more about the project.

**Comment by interestingtj** [comment]
> 你好，我是一名大三的学子，这是我主持的省级大创项目，我上传的代码只是我第一阶段的成果，第一阶段的成果有很多缺点，主要就是语音测谎没做好，数据集不够，如果你对我的项目感兴趣的话，可以从这两个方面去完善。我的论文还没有写，在导师的指导下，我开始了第二阶段的研究，目前我正在完善语音测谎以及模型融合，准备出了成果再写论文。同时我还在准备保研，要参加比赛，项目进度也拖的有点慢。毕竟不是我一个人的项目，没有同组成员的同意，一些关键性的数据、重要成果、代码我也不好发出来，如果你想了解更多的话，我在github上传了一个之前我答辩用的PPT，里面基本上描述了我们小组之前一段时间研究的思路和成果，希望能够帮到你。 Hello, I am a third-year university student. This is a provincial-level project that I presided over. The code I uploaded is only the result of my first phase. The first phase of the results has many shortcomings, mainly because the voice polygraph is not good and the data set is not enough. If you are interested in my project, you can improve it from these two aspects. My thesis has not been written yet, and under the guidance of my supervisor, I started the second phase of research. I am currently improving the voice polygraph and model fusion, and I will write the thesis after I have produced the results. At the same time, I'm preparing for postgraduate recommendation and I have to participate in the competition, so the progress of the project is a bit slow. After all, it's not my own project, without the consent of other members of the same group, I can't directly send out some key data, important results, and codes. If you want to know more, I posted a PPT of my defense on Github, which describes the ideas and results of our group's research. I hope it can help you.
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "jiaxin-scu/lie_detection" <notifications@github.com&gt;; 发送时间:&nbsp;2020年11月15日(星期天) 晚上6:54 收件人:&nbsp;"jiaxin-scu/lie_detection"<lie_detection@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;[jiaxin-scu/lie_detection] Papers about this project (#2) Hi. Is there any papers about your project lie_detection? I was wondering if I can learn more about the project. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by interestingtj** [comment]
That helps a lot. Thank you.
